version: "3.3"
services:
  nginxsotong:
    image: nginx:1.21.1
    networks:
      - sotong
    volumes:
      - /home/ubuntu/sotonggori/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static
      - /home/ubuntu/ReactForDocker:/data/build
    ports:
      - 80:80
  
  mariadbsotong:
    image: mariadb:10.5
    networks:
      - sotong
    volumes:
      - /home/ubuntu/database:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: sotongdb
      MARIADB_USER: project
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
    
  djangosotong:
    image: djangosotong:1.0
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_PASSWORD
    networks:
        - sotong
    volumes:
        - /home/ubuntu/sotonggori:/home/ubuntu/sotonggori
        - static:/home/ubuntu/sotonggori/staticfiles

networks:
  sotong:

volumes:
  static:

secrets:
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true