# Generated by Django 3.2 on 2021-08-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('day', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now='true')),
                ('organ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotongapp.organ')),
            ],
        ),
    ]
